apiVersion: installers.tmc.cloud.vmware.com/v1alpha1
kind: AgentInstall
metadata:
  name: tmc-agent-installer-config
  namespace: svc-tmc-c8
spec:
  operation: INSTALL
  registrationLink: https://openso.tmc.cloud.vmware.com/installer?id=aa25bf4af29af42e77bbbe7fe76081a4bbc2530b1fee2ba6da3a8b78c846e554&source=registration
